app:
  name: w7-site-manager
  env: ${APP_ENV-release}
  server: http
server:
  http:
    host: ${W7_SITE_MANAGER_SERVER_HOST-0.0.0.0}
    port: ${W7_SITE_MANAGER_SERVER_PORT-8000}
    tls:
      enable: ${W7_SITE_MANAGER_SERVER_TLS_ENABLE-false}
      port: ${W7_SITE_MANAGER_SERVER_TLS_PORT-}
      cert_file: ${W7_SITE_MANAGER_SERVER_TLS_CERT_FILE-}
      key_file: ${W7_SITE_MANAGER_SERVER_TLS_KEY_FILE-}
log:
  default:
    driver: stack
    channels:
      - file
      - console
  file:
    driver: file
    path: site-manager.log
    level: error
  console:
    driver: console
    level: info
database:
  default:
    driver: sqlite
    db_name: ${SQLITE_DIR}site-manager.db
    charset: utf8mb4
    show_sql: false
    prefix: ims_
    logger: db
  mysql:
    driver: mysql
    user_name: ${MYSQL_USERNAME-root}
    password: ${MYSQL_PASSWORD-123456}
    host: ${MYSQL_HOST-172.16.1.13}
    port: ${MYSQL_PORT-3306}
    db_name: ${MYSQL_DATABASE-w7_site_manager}
    charset: utf8mb4
    prefix: ims_
setting:
  oauth_token: ${OAUTH_TOKEN-rogtdpxguk}
  nginx:
    vhost_dir: ${NGINX_VHOST_DIR-/usr/local/etc/nginx/sites-enabled}
    web_root_dir: ${NGINX_WEB_DIR-/tmp/www}
  environment_attach_dir: /home/environment
  environment_server_dir: ${ENVIRONMENT_SERVER_ROOT}
  k8s:
    app_group: ${K8S_APP_GROUP-test}
    volume_name: ${K8S_VOLUME_NAME-test}
  webhook:
    remove_site_root_dir: ${WEBHOOK_REMOVE_SITE_ROOT_DIR-true}
