apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "site-manager.fullname" . }}
  labels:
    {{- include "site-manager.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.cluster.storageRWMode }}
  storageClassName: {{ .Values.cluster.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.cluster.storageSize | quote }}