{{- if .Values.webhook.enabled -}}
{{- $fullname := include "site-manager.fullname" . -}}
{{- $serviceName := $fullname -}}
{{- $namespace := .Release.Namespace -}}
{{- $secretName := printf "%s-webhook-tls" $fullname -}}
{{- $issuerName := printf "%s-webhook-selfsigned" $fullname -}}
{{- $certificateName := printf "%s-webhook-serving-cert" $fullname -}}
{{- $serviceDNS := printf "%s.%s.svc" $serviceName $namespace -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $issuerName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "site-manager.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $certificateName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "site-manager.labels" . | nindent 4 }}
spec:
  secretName: {{ $secretName }}
  duration: 8760h
  renewBefore: 720h
  dnsNames:
    - {{ $serviceName }}
    - {{ $serviceDNS }}
    - {{ printf "%s.%s.svc.cluster.local" $serviceName $namespace }}
  issuerRef:
    name: {{ $issuerName }}
    kind: Issuer
    group: cert-manager.io
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ $fullname }}-appgroup-delete
  labels:
    {{- include "site-manager.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ printf "%s/%s" $namespace $certificateName | quote }}
webhooks:
  - name: appgroup-delete.site-manager.w7.cc
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        namespace: {{ $namespace }}
        name: {{ $serviceName }}
        path: /webhook/appgroups/del
        port: {{ .Values.webhook.port }}
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
    reinvocationPolicy: Never
    rules:
      - operations:
          - DELETE
        apiGroups:
          - w7panel.w7.com
        apiVersions:
          - v1alpha1
        resources:
          - appgroups
        scope: Namespaced
    sideEffects: NoneOnDryRun
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
{{- end }}
