// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/w7panel/w7panel-sitemanager/common/entity"
)

func newSiteSetting(db *gorm.DB, opts ...gen.DOOption) siteSetting {
	_siteSetting := siteSetting{}

	_siteSetting.siteSettingDo.UseDB(db, opts...)
	_siteSetting.siteSettingDo.UseModel(&entity.SiteSetting{})

	tableName := _siteSetting.siteSettingDo.TableName()
	_siteSetting.ALL = field.NewAsterisk(tableName)
	_siteSetting.ID = field.NewInt32(tableName, "id")
	_siteSetting.SiteID = field.NewInt32(tableName, "site_id")
	_siteSetting.SettingKey = field.NewString(tableName, "setting_key")
	_siteSetting.SettingValue = field.NewString(tableName, "setting_value")
	_siteSetting.CreatedAt = field.NewTime(tableName, "created_at")

	_siteSetting.fillFieldMap()

	return _siteSetting
}

type siteSetting struct {
	siteSettingDo

	ALL          field.Asterisk
	ID           field.Int32
	SiteID       field.Int32
	SettingKey   field.String
	SettingValue field.String
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (s siteSetting) Table(newTableName string) *siteSetting {
	s.siteSettingDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s siteSetting) As(alias string) *siteSetting {
	s.siteSettingDo.DO = *(s.siteSettingDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *siteSetting) updateTableName(table string) *siteSetting {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.SiteID = field.NewInt32(table, "site_id")
	s.SettingKey = field.NewString(table, "setting_key")
	s.SettingValue = field.NewString(table, "setting_value")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *siteSetting) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *siteSetting) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["id"] = s.ID
	s.fieldMap["site_id"] = s.SiteID
	s.fieldMap["setting_key"] = s.SettingKey
	s.fieldMap["setting_value"] = s.SettingValue
	s.fieldMap["created_at"] = s.CreatedAt
}

func (s siteSetting) clone(db *gorm.DB) siteSetting {
	s.siteSettingDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s siteSetting) replaceDB(db *gorm.DB) siteSetting {
	s.siteSettingDo.ReplaceDB(db)
	return s
}

type siteSettingDo struct{ gen.DO }

type ISiteSettingDo interface {
	gen.SubQuery
	Debug() ISiteSettingDo
	WithContext(ctx context.Context) ISiteSettingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISiteSettingDo
	WriteDB() ISiteSettingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISiteSettingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISiteSettingDo
	Not(conds ...gen.Condition) ISiteSettingDo
	Or(conds ...gen.Condition) ISiteSettingDo
	Select(conds ...field.Expr) ISiteSettingDo
	Where(conds ...gen.Condition) ISiteSettingDo
	Order(conds ...field.Expr) ISiteSettingDo
	Distinct(cols ...field.Expr) ISiteSettingDo
	Omit(cols ...field.Expr) ISiteSettingDo
	Join(table schema.Tabler, on ...field.Expr) ISiteSettingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISiteSettingDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISiteSettingDo
	Group(cols ...field.Expr) ISiteSettingDo
	Having(conds ...gen.Condition) ISiteSettingDo
	Limit(limit int) ISiteSettingDo
	Offset(offset int) ISiteSettingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISiteSettingDo
	Unscoped() ISiteSettingDo
	Create(values ...*entity.SiteSetting) error
	CreateInBatches(values []*entity.SiteSetting, batchSize int) error
	Save(values ...*entity.SiteSetting) error
	First() (*entity.SiteSetting, error)
	Take() (*entity.SiteSetting, error)
	Last() (*entity.SiteSetting, error)
	Find() ([]*entity.SiteSetting, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.SiteSetting, err error)
	FindInBatches(result *[]*entity.SiteSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.SiteSetting) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISiteSettingDo
	Assign(attrs ...field.AssignExpr) ISiteSettingDo
	Joins(fields ...field.RelationField) ISiteSettingDo
	Preload(fields ...field.RelationField) ISiteSettingDo
	FirstOrInit() (*entity.SiteSetting, error)
	FirstOrCreate() (*entity.SiteSetting, error)
	FindByPage(offset int, limit int) (result []*entity.SiteSetting, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISiteSettingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s siteSettingDo) Debug() ISiteSettingDo {
	return s.withDO(s.DO.Debug())
}

func (s siteSettingDo) WithContext(ctx context.Context) ISiteSettingDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s siteSettingDo) ReadDB() ISiteSettingDo {
	return s.Clauses(dbresolver.Read)
}

func (s siteSettingDo) WriteDB() ISiteSettingDo {
	return s.Clauses(dbresolver.Write)
}

func (s siteSettingDo) Session(config *gorm.Session) ISiteSettingDo {
	return s.withDO(s.DO.Session(config))
}

func (s siteSettingDo) Clauses(conds ...clause.Expression) ISiteSettingDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s siteSettingDo) Returning(value interface{}, columns ...string) ISiteSettingDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s siteSettingDo) Not(conds ...gen.Condition) ISiteSettingDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s siteSettingDo) Or(conds ...gen.Condition) ISiteSettingDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s siteSettingDo) Select(conds ...field.Expr) ISiteSettingDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s siteSettingDo) Where(conds ...gen.Condition) ISiteSettingDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s siteSettingDo) Order(conds ...field.Expr) ISiteSettingDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s siteSettingDo) Distinct(cols ...field.Expr) ISiteSettingDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s siteSettingDo) Omit(cols ...field.Expr) ISiteSettingDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s siteSettingDo) Join(table schema.Tabler, on ...field.Expr) ISiteSettingDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s siteSettingDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISiteSettingDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s siteSettingDo) RightJoin(table schema.Tabler, on ...field.Expr) ISiteSettingDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s siteSettingDo) Group(cols ...field.Expr) ISiteSettingDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s siteSettingDo) Having(conds ...gen.Condition) ISiteSettingDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s siteSettingDo) Limit(limit int) ISiteSettingDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s siteSettingDo) Offset(offset int) ISiteSettingDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s siteSettingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISiteSettingDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s siteSettingDo) Unscoped() ISiteSettingDo {
	return s.withDO(s.DO.Unscoped())
}

func (s siteSettingDo) Create(values ...*entity.SiteSetting) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s siteSettingDo) CreateInBatches(values []*entity.SiteSetting, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s siteSettingDo) Save(values ...*entity.SiteSetting) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s siteSettingDo) First() (*entity.SiteSetting, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SiteSetting), nil
	}
}

func (s siteSettingDo) Take() (*entity.SiteSetting, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SiteSetting), nil
	}
}

func (s siteSettingDo) Last() (*entity.SiteSetting, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SiteSetting), nil
	}
}

func (s siteSettingDo) Find() ([]*entity.SiteSetting, error) {
	result, err := s.DO.Find()
	return result.([]*entity.SiteSetting), err
}

func (s siteSettingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.SiteSetting, err error) {
	buf := make([]*entity.SiteSetting, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s siteSettingDo) FindInBatches(result *[]*entity.SiteSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s siteSettingDo) Attrs(attrs ...field.AssignExpr) ISiteSettingDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s siteSettingDo) Assign(attrs ...field.AssignExpr) ISiteSettingDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s siteSettingDo) Joins(fields ...field.RelationField) ISiteSettingDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s siteSettingDo) Preload(fields ...field.RelationField) ISiteSettingDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s siteSettingDo) FirstOrInit() (*entity.SiteSetting, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SiteSetting), nil
	}
}

func (s siteSettingDo) FirstOrCreate() (*entity.SiteSetting, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SiteSetting), nil
	}
}

func (s siteSettingDo) FindByPage(offset int, limit int) (result []*entity.SiteSetting, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s siteSettingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s siteSettingDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s siteSettingDo) Delete(models ...*entity.SiteSetting) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *siteSettingDo) withDO(do gen.Dao) *siteSettingDo {
	s.DO = *do.(*gen.DO)
	return s
}
