// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/w7panel/w7panel-sitemanager/common/entity"
)

func newEnvironmentSetting(db *gorm.DB, opts ...gen.DOOption) environmentSetting {
	_environmentSetting := environmentSetting{}

	_environmentSetting.environmentSettingDo.UseDB(db, opts...)
	_environmentSetting.environmentSettingDo.UseModel(&entity.EnvironmentSetting{})

	tableName := _environmentSetting.environmentSettingDo.TableName()
	_environmentSetting.ALL = field.NewAsterisk(tableName)
	_environmentSetting.ID = field.NewInt32(tableName, "id")
	_environmentSetting.EnvironmentID = field.NewInt32(tableName, "environment_id")
	_environmentSetting.SettingKey = field.NewString(tableName, "setting_key")
	_environmentSetting.SettingValue = field.NewString(tableName, "setting_value")
	_environmentSetting.CreatedAt = field.NewTime(tableName, "created_at")

	_environmentSetting.fillFieldMap()

	return _environmentSetting
}

type environmentSetting struct {
	environmentSettingDo

	ALL           field.Asterisk
	ID            field.Int32
	EnvironmentID field.Int32
	SettingKey    field.String
	SettingValue  field.String
	CreatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (e environmentSetting) Table(newTableName string) *environmentSetting {
	e.environmentSettingDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e environmentSetting) As(alias string) *environmentSetting {
	e.environmentSettingDo.DO = *(e.environmentSettingDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *environmentSetting) updateTableName(table string) *environmentSetting {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt32(table, "id")
	e.EnvironmentID = field.NewInt32(table, "environment_id")
	e.SettingKey = field.NewString(table, "setting_key")
	e.SettingValue = field.NewString(table, "setting_value")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *environmentSetting) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *environmentSetting) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 5)
	e.fieldMap["id"] = e.ID
	e.fieldMap["environment_id"] = e.EnvironmentID
	e.fieldMap["setting_key"] = e.SettingKey
	e.fieldMap["setting_value"] = e.SettingValue
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e environmentSetting) clone(db *gorm.DB) environmentSetting {
	e.environmentSettingDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e environmentSetting) replaceDB(db *gorm.DB) environmentSetting {
	e.environmentSettingDo.ReplaceDB(db)
	return e
}

type environmentSettingDo struct{ gen.DO }

type IEnvironmentSettingDo interface {
	gen.SubQuery
	Debug() IEnvironmentSettingDo
	WithContext(ctx context.Context) IEnvironmentSettingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEnvironmentSettingDo
	WriteDB() IEnvironmentSettingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEnvironmentSettingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEnvironmentSettingDo
	Not(conds ...gen.Condition) IEnvironmentSettingDo
	Or(conds ...gen.Condition) IEnvironmentSettingDo
	Select(conds ...field.Expr) IEnvironmentSettingDo
	Where(conds ...gen.Condition) IEnvironmentSettingDo
	Order(conds ...field.Expr) IEnvironmentSettingDo
	Distinct(cols ...field.Expr) IEnvironmentSettingDo
	Omit(cols ...field.Expr) IEnvironmentSettingDo
	Join(table schema.Tabler, on ...field.Expr) IEnvironmentSettingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEnvironmentSettingDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEnvironmentSettingDo
	Group(cols ...field.Expr) IEnvironmentSettingDo
	Having(conds ...gen.Condition) IEnvironmentSettingDo
	Limit(limit int) IEnvironmentSettingDo
	Offset(offset int) IEnvironmentSettingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEnvironmentSettingDo
	Unscoped() IEnvironmentSettingDo
	Create(values ...*entity.EnvironmentSetting) error
	CreateInBatches(values []*entity.EnvironmentSetting, batchSize int) error
	Save(values ...*entity.EnvironmentSetting) error
	First() (*entity.EnvironmentSetting, error)
	Take() (*entity.EnvironmentSetting, error)
	Last() (*entity.EnvironmentSetting, error)
	Find() ([]*entity.EnvironmentSetting, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.EnvironmentSetting, err error)
	FindInBatches(result *[]*entity.EnvironmentSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.EnvironmentSetting) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEnvironmentSettingDo
	Assign(attrs ...field.AssignExpr) IEnvironmentSettingDo
	Joins(fields ...field.RelationField) IEnvironmentSettingDo
	Preload(fields ...field.RelationField) IEnvironmentSettingDo
	FirstOrInit() (*entity.EnvironmentSetting, error)
	FirstOrCreate() (*entity.EnvironmentSetting, error)
	FindByPage(offset int, limit int) (result []*entity.EnvironmentSetting, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEnvironmentSettingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e environmentSettingDo) Debug() IEnvironmentSettingDo {
	return e.withDO(e.DO.Debug())
}

func (e environmentSettingDo) WithContext(ctx context.Context) IEnvironmentSettingDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e environmentSettingDo) ReadDB() IEnvironmentSettingDo {
	return e.Clauses(dbresolver.Read)
}

func (e environmentSettingDo) WriteDB() IEnvironmentSettingDo {
	return e.Clauses(dbresolver.Write)
}

func (e environmentSettingDo) Session(config *gorm.Session) IEnvironmentSettingDo {
	return e.withDO(e.DO.Session(config))
}

func (e environmentSettingDo) Clauses(conds ...clause.Expression) IEnvironmentSettingDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e environmentSettingDo) Returning(value interface{}, columns ...string) IEnvironmentSettingDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e environmentSettingDo) Not(conds ...gen.Condition) IEnvironmentSettingDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e environmentSettingDo) Or(conds ...gen.Condition) IEnvironmentSettingDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e environmentSettingDo) Select(conds ...field.Expr) IEnvironmentSettingDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e environmentSettingDo) Where(conds ...gen.Condition) IEnvironmentSettingDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e environmentSettingDo) Order(conds ...field.Expr) IEnvironmentSettingDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e environmentSettingDo) Distinct(cols ...field.Expr) IEnvironmentSettingDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e environmentSettingDo) Omit(cols ...field.Expr) IEnvironmentSettingDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e environmentSettingDo) Join(table schema.Tabler, on ...field.Expr) IEnvironmentSettingDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e environmentSettingDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEnvironmentSettingDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e environmentSettingDo) RightJoin(table schema.Tabler, on ...field.Expr) IEnvironmentSettingDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e environmentSettingDo) Group(cols ...field.Expr) IEnvironmentSettingDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e environmentSettingDo) Having(conds ...gen.Condition) IEnvironmentSettingDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e environmentSettingDo) Limit(limit int) IEnvironmentSettingDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e environmentSettingDo) Offset(offset int) IEnvironmentSettingDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e environmentSettingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEnvironmentSettingDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e environmentSettingDo) Unscoped() IEnvironmentSettingDo {
	return e.withDO(e.DO.Unscoped())
}

func (e environmentSettingDo) Create(values ...*entity.EnvironmentSetting) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e environmentSettingDo) CreateInBatches(values []*entity.EnvironmentSetting, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e environmentSettingDo) Save(values ...*entity.EnvironmentSetting) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e environmentSettingDo) First() (*entity.EnvironmentSetting, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.EnvironmentSetting), nil
	}
}

func (e environmentSettingDo) Take() (*entity.EnvironmentSetting, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.EnvironmentSetting), nil
	}
}

func (e environmentSettingDo) Last() (*entity.EnvironmentSetting, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.EnvironmentSetting), nil
	}
}

func (e environmentSettingDo) Find() ([]*entity.EnvironmentSetting, error) {
	result, err := e.DO.Find()
	return result.([]*entity.EnvironmentSetting), err
}

func (e environmentSettingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.EnvironmentSetting, err error) {
	buf := make([]*entity.EnvironmentSetting, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e environmentSettingDo) FindInBatches(result *[]*entity.EnvironmentSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e environmentSettingDo) Attrs(attrs ...field.AssignExpr) IEnvironmentSettingDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e environmentSettingDo) Assign(attrs ...field.AssignExpr) IEnvironmentSettingDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e environmentSettingDo) Joins(fields ...field.RelationField) IEnvironmentSettingDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e environmentSettingDo) Preload(fields ...field.RelationField) IEnvironmentSettingDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e environmentSettingDo) FirstOrInit() (*entity.EnvironmentSetting, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.EnvironmentSetting), nil
	}
}

func (e environmentSettingDo) FirstOrCreate() (*entity.EnvironmentSetting, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.EnvironmentSetting), nil
	}
}

func (e environmentSettingDo) FindByPage(offset int, limit int) (result []*entity.EnvironmentSetting, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e environmentSettingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e environmentSettingDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e environmentSettingDo) Delete(models ...*entity.EnvironmentSetting) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *environmentSettingDo) withDO(do gen.Dao) *environmentSettingDo {
	e.DO = *do.(*gen.DO)
	return e
}
