// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameSiteSetting = "ims_site_setting"

// SiteSetting mapped from table <ims_site_setting>
type SiteSetting struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SiteID       int32     `gorm:"column:site_id;not null" json:"site_id"`
	SettingKey   string    `gorm:"column:setting_key;not null" json:"setting_key"`
	SettingValue string    `gorm:"column:setting_value" json:"setting_value"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName SiteSetting's table name
func (*SiteSetting) TableName() string {
	return TableNameSiteSetting
}
