// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameEnvironment = "ims_environment"

// Environment mapped from table <ims_environment>
type Environment struct {
	ID                 int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title              string    `gorm:"column:title;not null" json:"title"`
	Name               string    `gorm:"column:name;not null" json:"name"`
	AppName            string    `gorm:"column:app_name" json:"app_name"`
	Group_             string    `gorm:"column:group" json:"group"`
	Language           string    `gorm:"column:language" json:"language"`
	NginxVhostTemplate string    `gorm:"column:nginx_vhost_template" json:"nginx_vhost_template"`
	Version            string    `gorm:"column:version" json:"version"`
	UsedNum            int32     `gorm:"column:used_num" json:"used_num"`
	CreatedAt          time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt          time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Environment's table name
func (*Environment) TableName() string {
	return TableNameEnvironment
}
