// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameEnvironmentSetting = "ims_environment_setting"

// EnvironmentSetting mapped from table <ims_environment_setting>
type EnvironmentSetting struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	EnvironmentID int32     `gorm:"column:environment_id;not null" json:"environment_id"`
	SettingKey    string    `gorm:"column:setting_key;not null" json:"setting_key"`
	SettingValue  string    `gorm:"column:setting_value" json:"setting_value"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName EnvironmentSetting's table name
func (*EnvironmentSetting) TableName() string {
	return TableNameEnvironmentSetting
}
