apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "site-manager-nginx.fullname" . }}
  labels:
    {{- include "site-manager-nginx.labels" . | nindent 4 }}
  annotations:
    title: 站点管理-nginx
    w7.cc.app/title: 站点管理-nginx
    w7.cc/create-svc: 'false'
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "site-manager-nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "site-manager-nginx.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $defaultAffinity := dict "podAffinity" (dict "requiredDuringSchedulingIgnoredDuringExecution" (list (dict "labelSelector" (dict "matchLabels" (dict "app.kubernetes.io/name" "site-manager" "app.kubernetes.io/instance" .Release.Name "w7.cc/identifie" .Release.Name)) "topologyKey" "kubernetes.io/hostname"))) }}
      {{- $affinity := mergeOverwrite (deepCopy $defaultAffinity) (.Values.affinity | default dict) }}
      serviceAccountName: {{ include "site-manager-nginx.serviceAccountName" . }}
      runtimeClassName: sysbox-runc
      hostUsers: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "sh", "-c" ]
          args:
            - |
              CONF_PATH="{{.Values.global.NGINX_DIR}}/conf.d"
              NGINX_CONF="/etc/nginx/nginx.conf"
              mkdir -p "$CONF_PATH"

              DEFAULT_WORKER=2
              HOST_CPU=$(grep -c '^processor' /proc/cpuinfo)
              FINAL_WORKER=${NGINX_WORKER_PROCESSES:-$DEFAULT_WORKER}
              [ "$FINAL_WORKER" -eq "$HOST_CPU" ] && FINAL_WORKER=$DEFAULT_WORKER
              sed -i "s/\(worker_processes\).*;/\1 $FINAL_WORKER;/" "$NGINX_CONF"

              grep -q "include $CONF_PATH/\*.conf;" "$NGINX_CONF" || \
              sed -i "/include \/etc\/nginx\/conf.d\/\*.conf;/a\    include $CONF_PATH/*.conf;" "$NGINX_CONF"

              nginx -g 'daemon off;'
          env:
            - name: NGINX_WORKER_PROCESSES
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
                  divisor: '1'
          volumeMounts:
            - mountPath: {{.Values.global.NGINX_DIR}}
              name: site-storage
              subPath: nginx-dir
            - mountPath: {{.Values.global.NGINX_WEB_DIR}}
              name: site-storage
              subPath: nginx-web-dir
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: site-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-site-manager
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        {{- toYaml $affinity | nindent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
